import $ from "jquery";

import { InputBinding } from "./InputBinding";
import { $escape, hasOwnProperty, updateLabel } from "../../utils";
import { CheckedHTMLElement } from "./checkbox";

type CheckboxGroupHTMLElement = CheckedHTMLElement;
type ValueLabelObject = {
  value: any;
  label: string;
};
type CheckboxGroupReceiveMessageData = {
  options?: any;
  value?: any;
  label: string;
};

class CheckboxGroupInputBinding extends InputBinding {
  find(scope: HTMLElement): JQuery<HTMLElement> {
    return $(scope).find(".shiny-input-checkboxgroup");
  }

  getValue(el: CheckboxGroupHTMLElement): Array<CheckboxGroupHTMLElement> {
    // Select the checkbox objects that have name equal to the grouping div's id
    const $objs = $('input:checkbox[name="' + $escape(el.id) + '"]:checked');
    const values = new Array($objs.length);

    for (let i = 0; i < $objs.length; i++) {
      values[i] = ($objs[i] as CheckboxGroupHTMLElement).value;
    }
    return values;
  }
  setValue(el: HTMLElement, value: Array<string> | string): void {
    // Clear all checkboxes
    $('input:checkbox[name="' + $escape(el.id) + '"]').prop("checked", false);

    // Accept array
    if (value instanceof Array) {
      for (let i = 0; i < value.length; i++) {
        $(
          'input:checkbox[name="' +
            $escape(el.id) +
            '"][value="' +
            $escape(value[i]) +
            '"]'
        ).prop("checked", true);
      }
      // Else assume it's a single value
    } else {
      $(
        'input:checkbox[name="' +
          $escape(el.id) +
          '"][value="' +
          $escape(value) +
          '"]'
      ).prop("checked", true);
    }
  }
  getState(el: CheckboxGroupHTMLElement): {
    label: string;
    value: any;
    options: Array<ValueLabelObject>;
  } {
    const $objs = $(
      'input:checkbox[name="' + $escape(el.id) + '"]'
    ) as JQuery<CheckboxGroupHTMLElement>;

    // Store options in an array of objects, each with with value and label
    const options = new Array($objs.length);

    for (let i = 0; i < options.length; i++) {
      options[i] = { value: $objs[i].value, label: this._getLabel($objs[i]) };
    }

    return {
      label: this._getLabelNode(el).text(),
      value: this.getValue(el),
      options: options,
    };
  }
  receiveMessage(
    el: CheckboxGroupHTMLElement,
    data: CheckboxGroupReceiveMessageData
  ): void {
    const $el = $(el);

    // This will replace all the options
    if (hasOwnProperty(data, "options")) {
      // Clear existing options and add each new one
      $el.find("div.shiny-options-group").remove();
      // Backward compatibility: for HTML generated by shinybootstrap2 package
      $el.find("label.checkbox").remove();
      $el.append(data.options);
    }

    if (hasOwnProperty(data, "value")) this.setValue(el, data.value);

    updateLabel(data.label, this._getLabelNode(el));

    $(el).trigger("change");
  }
  subscribe(
    el: CheckboxGroupHTMLElement,
    callback: (x: boolean) => void
  ): void {
    $(el).on("change.checkboxGroupInputBinding", function () {
      callback(false);
    });
  }
  unsubscribe(el: CheckboxGroupHTMLElement): void {
    $(el).off(".checkboxGroupInputBinding");
  }

  // Get the DOM element that contains the top-level label
  _getLabelNode(el: CheckboxGroupHTMLElement): JQuery<HTMLElement> {
    return $(el).find('label[for="' + $escape(el.id) + '"]');
  }
  // Given an input DOM object, get the associated label. Handles labels
  // that wrap the input as well as labels associated with 'for' attribute.
  _getLabel(obj: HTMLElement): string | null {
    // If <label><input /><span>label text</span></label>
    if ((obj.parentNode as HTMLElement).tagName === "LABEL") {
      return $(obj.parentNode).find("span").text().trim();
    }

    return null;
  }
  // Given an input DOM object, set the associated label. Handles labels
  // that wrap the input as well as labels associated with 'for' attribute.
  _setLabel(obj: HTMLElement, value: string): null {
    // If <label><input /><span>label text</span></label>
    if ((obj.parentNode as HTMLElement).tagName === "LABEL") {
      $(obj.parentNode).find("span").text(value);
    }

    return null;
  }
}

export { CheckboxGroupInputBinding };
export type { CheckboxGroupReceiveMessageData };
