import $ from "jquery";
import { InputBinding } from ".";
import { $escape, hasOwnProperty, updateLabel } from "../../utils";

type RadioHTMLElement = HTMLInputElement;

type ValueLabelObject = {
  value: any;
  label: string;
};

class RadioInputBinding extends InputBinding {
  find(scope: HTMLElement): JQuery<HTMLElement> {
    return $(scope).find(".shiny-input-radiogroup");
  }
  getValue(el: RadioHTMLElement): string | number | string[] | null {
    // Select the radio objects that have name equal to the grouping div's id
    const checkedItems = $(
      'input:radio[name="' + $escape(el.id) + '"]:checked'
    );

    if (checkedItems.length === 0) {
      // If none are checked, the input will return null (it's the default on load,
      // but it wasn't emptied when calling updateRadioButtons with character(0)
      return null;
    }

    return checkedItems.val();
  }
  setValue(el: RadioHTMLElement, value: string): void {
    if ($.isArray(value) && value.length === 0) {
      // Removing all checked item if the sent data is empty
      $('input:radio[name="' + $escape(el.id) + '"]').prop("checked", false);
    } else {
      $(
        'input:radio[name="' +
          $escape(el.id) +
          '"][value="' +
          $escape(value) +
          '"]'
      ).prop("checked", true);
    }
  }
  getState(
    el: RadioHTMLElement
  ): {
    label: string;
    value: string | number | string[];
    options: Array<ValueLabelObject>;
  } {
    const $objs = $(
      'input:radio[name="' + $escape(el.id) + '"]'
    ) as JQuery<RadioHTMLElement>;

    // Store options in an array of objects, each with with value and label
    const options = new Array($objs.length);

    for (let i = 0; i < options.length; i++) {
      options[i] = { value: $objs[i].value, label: this._getLabel($objs[i]) };
    }

    return {
      label: this._getLabelNode(el).text(),
      value: this.getValue(el),
      options: options,
    };
  }
  receiveMessage(
    el: RadioHTMLElement,
    data: {
      value?: string;
      options?: Array<ValueLabelObject>;
      label: string;
    }
  ): void {
    const $el = $(el);
    // This will replace all the options

    if (hasOwnProperty(data, "options")) {
      // Clear existing options and add each new one
      $el.find("div.shiny-options-group").remove();
      // Backward compatibility: for HTML generated by shinybootstrap2 package
      $el.find("label.radio").remove();
      // TODO-barret; IDK what this line is doing
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      $el.append(data.options);
    }

    if (hasOwnProperty(data, "value")) this.setValue(el, data.value);

    updateLabel(data.label, this._getLabelNode(el));

    $(el).trigger("change");
  }
  subscribe(el: RadioHTMLElement, callback: (x: boolean) => void): void {
    $(el).on("change.radioInputBinding", function () {
      callback(false);
    });
  }
  unsubscribe(el: RadioHTMLElement): void {
    $(el).off(".radioInputBinding");
  }
  // Get the DOM element that contains the top-level label
  _getLabelNode(el: RadioHTMLElement): JQuery<HTMLElement> {
    return $(el)
      .parent()
      .find('label[for="' + $escape(el.id) + '"]');
  }
  // Given an input DOM object, get the associated label. Handles labels
  // that wrap the input as well as labels associated with 'for' attribute.
  _getLabel(obj: HTMLElement): string | null {
    // If <label><input /><span>label text</span></label>
    if ((obj.parentNode as HTMLElement).tagName === "LABEL") {
      return $(obj.parentNode).find("span").text().trim();
    }

    return null;
  }
  // Given an input DOM object, set the associated label. Handles labels
  // that wrap the input as well as labels associated with 'for' attribute.
  _setLabel(obj: HTMLElement, value: string): null {
    // If <label><input /><span>label text</span></label>
    if ((obj.parentNode as HTMLElement).tagName === "LABEL") {
      $(obj.parentNode).find("span").text(value);
    }

    return null;
  }
}

export { RadioInputBinding };
