root: true
env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:jest/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
  - 'plugin:jest-dom/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - jest-dom
  - unicorn
rules:
  "@typescript-eslint/explicit-function-return-type":
    - off
  "@typescript-eslint/no-explicit-any":
    - off
  "@typescript-eslint/explicit-module-boundary-types":
    - error

  default-case:
    - error
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - avoid-escape
  semi:
    - error
    - always
  newline-after-var:
    - error
    - always
  dot-location:
    - error
    - property

  camelcase:
    # - error
    - "off"

  unicorn/filename-case:
    - error
    - case: camelCase

  "@typescript-eslint/consistent-type-imports":
    - error
  "@typescript-eslint/naming-convention":
    - error

    - selector: default
      format: [camelCase]

    - selector: method
      modifiers: [private]
      format: [camelCase]
      leadingUnderscore: require
    - selector: method
      modifiers: [protected]
      format: [camelCase]
      leadingUnderscore: require

    - selector: variable
      format: [camelCase]
      trailingUnderscore: forbid
      leadingUnderscore: forbid

    - selector: parameter
      format: [camelCase]
      trailingUnderscore: allow
      leadingUnderscore: forbid

    - selector: [enum, enumMember]
      format: [PascalCase]

    - selector: typeLike
      format: [PascalCase]
      custom:
        regex: "(t|T)ype$"
        match: false
