library(magrittr)

version <- "3.7.1"
version_types <- "3.5.32"

# Install first, then vendor out of `node_modules` rather than off the CDN, so
# that `package.json` is the single record of which version ships. That is what
# lets the `license-note` step in the routine workflow report jQuery's license
# automatically -- see LICENSE.note.
withr::with_dir(
  rprojroot::find_package_root_file(),
  {
    exit_code <- system(paste0("npm install --save-dev --save-exact jquery@", version))
    if (exit_code != 0) stop("npm could not install jquery")

    exit_code <- system(paste0("npm install --save --save-exact @types/jquery@", version_types))
    if (exit_code != 0) stop("npm could not install @types/jquery")
  }
)

# The npm `dist/` files are byte-identical to the CDN ones, apart from the
# source map comment that jQuery strips from its CDN builds and that this
# script appends below.
jq_copy_dist <- function() {
  Map(
    src = c("jquery.min.js", "jquery.min.map", "jquery.js"),
    dst = c("jquery.min.js", "jquery.min.js.map", "jquery.js"),
    f = function(src, dst) {
      file.copy(
        rprojroot::find_package_root_file("node_modules", "jquery", "dist", src),
        file.path("inst", "www", "shared", dst),
        overwrite = TRUE
      )
    }
  )
}

jq_copy_dist()

# Add in source map location
# Required given comments in https://blog.jquery.com/2014/01/24/jquery-1-11-and-2-1-released/
jquery_min_js <- file.path("inst", "www", "shared", "jquery.min.js")
# Point to the version-less source map file
cat(
  file = jquery_min_js,
  append = TRUE,
  "//# sourceMappingURL=jquery.min.js.map\n"
)
# Replace versioned file source locations with version-less file source
# locations (~2 locations)
jquery_min_js_map <- paste0(jquery_min_js, ".map")
brio::read_lines(jquery_min_js_map) %>%
  gsub(
    gsub("\\.", "\\\\.", paste0("\"jquery-", version, ".")),
    "\"jquery.",
    .
  ) %>%
  brio::write_lines(jquery_min_js_map)

download.file(
  "https://raw.githubusercontent.com/jquery/jquery/master/AUTHORS.txt",
  "inst/www/shared/jquery-AUTHORS.txt"
)

writeLines(
  c(
    "# Generated by tools/updatejQuery.R; do not edit by hand",
    sprintf('version_jquery <- "%s"', version)
  ),
  rprojroot::find_package_root_file("R", "version_jquery.R")
)
