version <- "3.6.0"

jq_cdn_download <- function(version) {
  srcs <- c(".min.js", ".min.map", ".js")
  download.file(
    file.path("https://code.jquery.com", paste0("jquery-", version, srcs)),
    file.path("inst", "www", "shared",  paste0("jquery", srcs))
  )
}

jq_cdn_download(version)

download.file(
  "https://raw.githubusercontent.com/jquery/jquery/master/AUTHORS.txt",
  "inst/www/shared/jquery-AUTHORS.txt"
)

dest_file <- rprojroot::find_package_root_file("R", "version_jquery.R")

writeLines(
  c(
    "# Generated by tools/updatejQuery.R; do not edit by hand",
    sprintf('version_jquery <- "%s"', version)
  ),
  find_package_root_file("R", "version_jquery.R")
)
