# source("tools/updateHtmltoolsMan.R")
# Will add all functions aliased in the htmltools man files below
# Will save all reexports to `./R/reexport-htmltools.R` and document to enforce all re-exports


local({

  `%>%` <- magrittr::`%>%`

  # pre document
  devtools::document()

  namespace_line_count <- length(readLines(rprojroot::find_package_root_file("NAMESPACE")))

  # tags are returned from newest to oldest. (Newest being first)
  latest_tag_name <- jsonlite::fromJSON("https://api.github.com/repos/rstudio/htmltools/tags", simplifyDataFrame = FALSE)[[1]]$name
  htmltools_github_man_location <- paste0("https://raw.githubusercontent.com/rstudio/htmltools/", latest_tag_name, "/man/")

  local_man_folder <- rprojroot::find_package_root_file("man")
  local_htmltools_r_file <- rprojroot::find_package_root_file("R/reexport-htmltools.R")

  alias_list <- list()

  add_aliases <- function(man_file, ignore = NULL) {
    lines <- paste0(htmltools_github_man_location, man_file) %>%
      readLines() %>%
      { .[-(1:2)] } # remove first two roxygen2 comments

    alias_list[[man_file]] <<-
      lines[grepl("\\alias{", lines, fixed = TRUE)] %>%
      sub("\\alias{", "", ., fixed = TRUE) %>%
      sub("}$", "", .) %>%
      setdiff(ignore) %>%
      list(functions = ., file = man_file)
  }
  add_aliases("builder.Rd", ignore = c("builder"))
  add_aliases("tag.Rd")
  add_aliases("HTML.Rd")
  add_aliases("include.Rd", ignore = c("include"))
  add_aliases("singleton.Rd")
  add_aliases("validateCssUnit.Rd")
  add_aliases("htmlTemplate.Rd")
  add_aliases("suppressDependencies.Rd")
  add_aliases("withTags.Rd")


  alias_list %>%
    vapply(FUN.VALUE = character(1), USE.NAMES = FALSE,
      function(alias_item) {
        beginning <- "# htmltools "
        paste0(
          beginning, alias_item$file, " ", paste0(rep("-", 80 - nchar(beginning) - nchar(alias_item$file) - 1), collapse = ""), "\n",
          ### https://github.com/tidyverse/dplyr/blob/713849e31b1f7b217154586d30aa169749075481/R/reexport-tibble.r
          # #' @importFrom tibble data_frame
          # #' @export
          # tibble::data_frame
          ###
          paste0(collapse = "\n",
            "\n",
            "#' @importFrom htmltools ", alias_item$functions, "\n",
            "#' @export\n",
            "htmltools::", alias_item$functions
          ),
          "\n"
        )
      }
    ) %>%
    paste0(collapse = "\n\n") %>%
    paste0(
      "####\n",
      "# Generated by `./tools/updateHtmltoolsMan.R`: do not edit by hand\n",
      "# Please call `source('tools/updateHtmltoolsMan.R') from the root folder to update`\n",
      "####\n",
      "\n",
      "\n",
      .
    ) %>%
    writeLines(local_htmltools_r_file)
  message("Updated: ", local_htmltools_r_file)

  # document new functions
  devtools::document()
  namespace_line_count_new <- length(readLines(rprojroot::find_package_root_file("NAMESPACE")))

  new_version <-
    paste0("https://raw.githubusercontent.com/rstudio/htmltools/", latest_tag_name, "/DESCRIPTION") %>%
    url() %>%
    read.dcf() %>%
    as.data.frame() %>%
    {.$Version[1]} %>%
    as.character()

  message("\n")
  if (namespace_line_count_new == namespace_line_count) {
    message("The NAMESPACE exports did NOT change by copying in the `htmltools` man files")
    message()
    message("Possible `htmltools` version requirement to add to DESCRIPTION file:\nImports:\n    htmltools (>= ", new_version, ")")
  } else {
    message("The NAMESPACE exports CHANGED by copying in the `htmltools` man files")
    message()
    message("`htmltools` version requirement to add to DESCRIPTION file:\nImports:\n    htmltools (>= ", new_version, ")")
  }


  # validate that all man files are autogenerated
  first_man_file_line <-
    dir("man", full.names = TRUE) %>%
    setNames(., .) %>%
    lapply(readLines) %>%
    lapply(head, 1)
  is_all_roxygen <-
    first_man_file_line %>%
    unique() %>%
    length() %>%
    magrittr::equals(1)

  if (!is_all_roxygen) {
    str(first_man_file_line[vapply(first_man_file_line, function(txt) !grepl("Generated by roxygen2:", txt, fixed = TRUE), logical(1))])
    stop("Not every file is auto generated by roxygen.  Fix this!")
  }

})
