#!/usr/bin/env Rscript

# This script vendors strftime-min.js out of `node_modules`,
# https://github.com/samsonjs/strftime

# This script can be sourced from RStudio, or run with Rscript.

version <- "0.9.2"
destdir <- rprojroot::find_package_root_file(
  "inst",
  "www",
  "shared",
  "strftime"
)

# Install first, then vendor out of `node_modules` rather than off GitHub, so
# that `package.json` is the single record of which version ships. That is what
# lets the `license-note` step in the routine workflow report strftime's
# license automatically -- see LICENSE.note.
withr::with_dir(
  rprojroot::find_package_root_file(),
  {
    exit_code <- system(paste0("npm install --save-dev --save-exact strftime@", version))
    if (exit_code != 0) stop("npm could not install strftime")
  }
)

file.copy(
  rprojroot::find_package_root_file("node_modules", "strftime", "strftime-min.js"),
  file.path(destdir, "strftime-min.js"),
  overwrite = TRUE
)

writeLines(
  c(
    "# Generated by tools/updateStrftime.R; do not edit by hand",
    sprintf('version_strftime <- "%s"', version)
  ),
  rprojroot::find_package_root_file("R", "version_strftime.R")
)
