spinners_zip <- withr::local_tempfile(pattern = "spinners-", fileext = ".zip")
download.file(
  "https://github.com/n3r4zzurr0/svg-spinners/archive/refs/heads/main.zip",
  spinners_zip
)

files <- zip::zip_list(spinners_zip)

svg_spinners <- grep("^svg-spinners-main/svg-smil/.", files$filename, value = TRUE)

dir_spinners <- here::here("inst", "www", "shared", "busy-indicators", "spinners")
if (!dir.exists(dir_spinners)) dir.create(dir_spinners, recursive = TRUE)

zip::unzip(
  spinners_zip,
  files = svg_spinners,
  exdir = dir_spinners,
  junkpaths = TRUE
)

zip::unzip(
  spinners_zip,
  files = "svg-spinners-main/LICENSE",
  exdir = dir_spinners,
  junkpaths = TRUE
)

spinners <- file.path(dir_spinners, basename(svg_spinners))

for (spinner in spinners) {
  svg <- readLines(spinner, warn = FALSE)
  svg <- sub('width="\\d+" height="\\d+" ', "", svg)
  writeLines(svg, spinner)
}

spinner_names <- sub("[.]svg$", "", basename(svg_spinners))

writeLines(
  c(
    "# Generated by tools/updateSpinners.R: do not edit by hand",
    ".spinner_types <-",
    paste(" ", deparse(spinner_names))
  ),
  here::here("R/busy-indicators-spinners.R")
)
