#!/usr/bin/env Rscript
library(rprojroot)

## -----------------------------------------------------------------
## First, download the main selectize.js and css
## -----------------------------------------------------------------

version <- "0.15.2"
types_version <- "0.15.2"

dest_dir <- find_package_root_file("inst/www/shared/selectize")
tag <- paste0("v", version)
dest_file <- file.path(tempdir(), paste0("selectize.js-", version, ".zip"))
url <- sprintf("https://github.com/selectize/selectize.js/archive/%s.zip", tag)

download.file(url, dest_file)
unzipped <- tempdir()
unzip(dest_file, exdir = unzipped)

unlink(dest_dir, recursive = TRUE)

selectize_dir <- file.path(unzipped, paste0("selectize.js-", version))

dir.create(file.path(dest_dir, "js"), recursive = TRUE)
file.copy(
  file.path(selectize_dir, "dist", "js", "selectize.min.js"),
  file.path(dest_dir, "js"),
  overwrite = TRUE
)

dir.create(file.path(dest_dir, "css"), recursive = TRUE)
file.copy(
  file.path(selectize_dir, "dist", "css", "selectize.bootstrap3.css"),
  file.path(dest_dir, "css"),
  overwrite = TRUE
)

dir.create(file.path(dest_dir, "scss"), recursive = TRUE)
file.copy(
  file.path(selectize_dir, "src", "scss"),
  dest_dir,
  overwrite = TRUE,
  recursive = TRUE
)

# Remove the unnecessary imports of Bootstrap from scss files
remove_bootstrap_imports <- function(f) {
  txt <- readLines(f)
  txt <- txt[!grepl('@import\\s+"lib/bootstrap', txt)]
  writeLines(txt, f)
}

lapply(
  dir(file.path(dest_dir, "scss"), full.names = TRUE),
  remove_bootstrap_imports
)

# Sass code imports the plugins
dir.create(file.path(dest_dir, "plugins"), recursive = TRUE)
file.copy(
  file.path(selectize_dir, "src", "plugins"),
  dest_dir,
  overwrite = TRUE,
  recursive = TRUE
)

file.remove(
  # Definitely don't need less files
  Sys.glob(file.path(dest_dir, "plugins", "*", "*.less")),
  # Probably don't need js files?
  Sys.glob(file.path(dest_dir, "plugins", "*", "*.js"))
)

## -----------------------------------------------------------------
## Second, download accessibility plugin
## -----------------------------------------------------------------

ally_version <- "927d81e9ea86acac1724d57b2ce9f3c962fd34c4"
url <- sprintf("https://github.com/SLMNBJ/selectize-plugin-a11y/archive/%s.zip", ally_version)
dest_file <- file.path(tempdir(), paste0("selectize-plugin-a11y-", ally_version, ".zip"))
download.file(url, dest_file)

unzipped <- tempdir()
unzip(dest_file, exdir = unzipped)

dir.create(file.path(dest_dir, "accessibility", "js"), recursive = TRUE)
file.copy(
  file.path(unzipped, paste0("selectize-plugin-a11y-", ally_version), "selectize-plugin-a11y.js"),
  file.path(dest_dir, "accessibility", "js"),
  overwrite = TRUE
)


# =============================================================================
# Apply patches
# =============================================================================
# The version of selectize-plugin-a11y that we use is modified from the base version
# in the following ways:
# * In our version, each option item has their own unique id to be announced to screen readers when selection changes.

patch_dir <- find_package_root_file("tools/selectize-patches")

for (patch in list.files(patch_dir, full.names = TRUE)) {
  tryCatch(
    {
      message(sprintf("Applying %s", basename(patch)))
      withr::with_dir(find_package_root_file(), system(sprintf("git apply %s", patch)))
    },
    error = function(e) {
      quit(save = "no", status = 1)
    }
  )
}

# =============================================================================
# Add versions to files
# =============================================================================
writeLines(
  c(
    "# Generated by tools/updateSelectize.R; do not edit by hand",
    sprintf('version_selectize <- "%s"', version)
  ),
  rprojroot::find_package_root_file("R", "version_selectize.R")
)

# Update TypeScript installation
withr::with_dir(
  rprojroot::find_package_root_file(),
  {
    exit_code <- system(paste0("yarn add --dev @selectize/selectize@", version))
    if (exit_code != 0) stop("yarn could not install selectize")
  }
)

# =============================================================================
# Generate minified js
# =============================================================================
withr::with_dir(find_package_root_file("srcts"), system("yarn build"))
