# Generated by scrts/extras/busy-indicators/spinners/_update_spinners.R: do not edit by hand
.spinner_names <-
  c("12-dots-scale-rotate", "180-ring-with-bg", "180-ring", "270-ring-with-bg", 
  "270-ring", "3-dots-bounce", "3-dots-fade", "3-dots-move", "3-dots-rotate", 
  "3-dots-scale-middle", "3-dots-scale", "6-dots-rotate", "6-dots-scale-middle", 
  "6-dots-scale", "8-dots-rotate", "90-ring-with-bg", "90-ring", 
  "bars-fade", "bars-rotate-fade", "bars-scale-fade", "bars-scale-middle", 
  "bars-scale", "blocks-scale", "blocks-shuffle-2", "blocks-shuffle-3", 
  "blocks-wave", "bouncing-ball", "clock", "dot-revolve", "eclipse-half", 
  "eclipse", "gooey-balls-1", "gooey-balls-2", "pulse-2", "pulse-3", 
  "pulse-multiple", "pulse-ring", "pulse-rings-2", "pulse-rings-3", 
  "pulse-rings-multiple", "pulse", "ring-resize", "tadpole", "wifi-fade", 
  "wifi", "wind-toy")
