#' Create date input
#'
#' Creates a text input which, when clicked on, brings up a calendar that
#' the user can click on to select dates.
#'
#' The date \code{format} string specifies how the date will be displayed in
#' the browser. It allows the following values:
#'
#' \itemize{
#'   \item \code{yy} Year without century (12)
#'   \item \code{yyyy} Year with century (2012)
#'   \item \code{mm} Month number, with leading zero (01-12)
#'   \item \code{m} Month number, without leading zero (1-12)
#'   \item \code{M} Abbreviated month name
#'   \item \code{MM} Full month name
#'   \item \code{dd} Day of month with leading zero
#'   \item \code{d} Day of month without leading zero
#'   \item \code{D} Abbreviated weekday name
#'   \item \code{DD} Full weekday name
#' }
#'
#' @inheritParams textInput
#' @param value The starting date. Either a Date object, or a string in
#'   \code{yyyy-mm-dd} format. If NULL (the default), will use the current date
#'   in the client's time zone.
#' @param min The minimum allowed date. Either a Date object, or a string in
#'   \code{yyyy-mm-dd} format.
#' @param max The maximum allowed date. Either a Date object, or a string in
#'   \code{yyyy-mm-dd} format.
#' @param format The format of the date to display in the browser. Defaults to
#'   \code{"yyyy-mm-dd"}.
#' @param startview The date range shown when the input object is first clicked.
#'   Can be "month" (the default), "year", or "decade".
#' @param weekstart Which day is the start of the week. Should be an integer
#'   from 0 (Sunday) to 6 (Saturday).
#' @param language The language used for month and day names. Default is "en".
#'   Other valid values include "ar", "az", "bg", "bs", "ca", "cs", "cy", "da",
#'   "de", "el", "en-AU", "en-GB", "eo", "es", "et", "eu", "fa", "fi", "fo",
#'   "fr-CH", "fr", "gl", "he", "hr", "hu", "hy", "id", "is", "it-CH", "it",
#'   "ja", "ka", "kh", "kk", "ko", "kr", "lt", "lv", "me", "mk", "mn", "ms",
#'   "nb", "nl-BE", "nl", "no", "pl", "pt-BR", "pt", "ro", "rs-latin", "rs",
#'   "ru", "sk", "sl", "sq", "sr-latin", "sr", "sv", "sw", "th", "tr", "uk",
#'   "vi", "zh-CN", and "zh-TW".
#' @param autoclose Close immediately when a date is selected (\code{TRUE} or
#'   \code{FALSE}).
#' @param multidate Enable multidate. Either \code{TRUE} or \code{FALSE} or an
#'   integer stating how  many dates can be selected, dropping the oldest dates
#'   from the list when the number is exceeded. The input's value is set to a
#'   string generated by joining the dates, formatted, with
#'   \code{multidateSeparator}.
#' @param multidateSeparator The string that will appear between dates when
#'   generating the multidate input's value.
#' @param orientation Location of the popup's anchor. A space-separated string
#'   consisting of one or two of \code{left} or \code{right}, \code{top}
#'   or \code{bottom}, and \code{auto}.
#' @param title Title on the top of the date picker.
#' @param todayBtn Display a "Today" button. If \code{TRUE} it will move the
#'   current date into view. If \code{"linked"} the current date will also be
#'   selected.
#' @param todayHighlight Highlight the current date.
#' @param toggleActive If \code{TRUE}, selecting the currently active date in
#'   the datepicker will unset the respective date. Always \code{TRUE} when
#'   multidate is being used.
#' @param calendarWeeks Show week numbers to the left of week rows (\code{TRUE}
#' or \code{FALSE}).
#' @param clearBtn Display a "Clear" button (\code{TRUE} or \code{FALSE}).
#' @param datesDisabled Disabled dates. Either a Date object, a string
#'   in \code{yyyy-mm-dd} format or a vector.
#' @param daysOfWeekDisabled Disabled days of week. Should be an integer from 0
#'   (Sunday) to 6 (Saturday) or a vector.
#' @param daysOfWeekHighlighted Highlighted days of week. Should be an integer
#'   from 0 (Sunday) to 6 (Saturday) or a vector.
#' @param immediateUpdates Update the input value immediately when selecting a
#'   year or month (\code{TRUE} or \code{FALSE}).
#' @param keyboardNavigation Allow date navigation by arrow keys (\code{TRUE} or
#'   \code{FALSE}).
#'
#' @family input elements
#' @seealso \code{\link{dateRangeInput}}, \code{\link{updateDateInput}}
#'
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'
#' ui <- fluidPage(
#'   dateInput("date1", "Date:", value = "2012-02-29"),
#'
#'   # Default value is the date in client's time zone
#'   dateInput("date2", "Date:"),
#'
#'   # value is always yyyy-mm-dd, even if the display format is different
#'   dateInput("date3", "Date:", value = "2012-02-29", format = "mm/dd/yy"),
#'
#'   # Pass in a Date object
#'   dateInput("date4", "Date:", value = Sys.Date()-10),
#'
#'   # Use different language and different first day of week
#'   dateInput("date5", "Date:",
#'           language = "ru",
#'           weekstart = 1),
#'
#'   # Start with decade view instead of default month view
#'   dateInput("date6", "Date:",
#'             startview = "decade")
#' )
#'
#' shinyApp(ui, server = function(input, output) { })
#' }
#' @export
dateInput <- function(inputId, label, value = NULL, min = NULL, max = NULL,
  format = "yyyy-mm-dd", startview = "month", weekstart = 0, language = "en",
  autoclose = FALSE, multidate = FALSE, multidateSeparator = ",",
  orientation = "auto", title = NULL, todayBtn = FALSE, todayHighlight = FALSE,
  toggleActive = FALSE, calendarWeeks = FALSE, clearBtn = FALSE,
  datesDisabled = NULL, daysOfWeekDisabled = NULL, daysOfWeekHighlighted = NULL,
  immediateUpdates = FALSE, keyboardNavigation = TRUE, width = NULL) {

  # If value is a date object, convert it to a string with yyyy-mm-dd format
  # Same for min and max
  if (inherits(value, "Date"))  value <- format(value, "%Y-%m-%d")
  if (inherits(min,   "Date"))  min   <- format(min,   "%Y-%m-%d")
  if (inherits(max,   "Date"))  max   <- format(max,   "%Y-%m-%d")

  value <- restoreInput(id = inputId, default = value)

  inputTag <- tags$input(
    type = "text",
    class = "form-control",
    `data-date-language` = language,
    `data-date-week-start` = weekstart,
    `data-date-format` = format,
    `data-date-start-view` = startview,
    `data-date-multidate-separator` = multidateSeparator,
    `data-date-orientation` = orientation,
    `data-date-title` = title,
    `data-min-date` = min,
    `data-max-date` = max,
    `data-initial-date` = value
  )

  if (!is.null(autoclose) && autoclose)
    inputTag$attribs$`data-date-autoclose` <- "true"

  # When numeric, multidate is the maximum number of dates that can be selected
  if (!is.null(multidate) && multidate == T) {
    if (is.numeric(multidate)) {
      inputTag$attribs$`data-date-multidate` <- multidate
    } else {
      inputTag$attribs$`data-date-multidate` <- "true"
    }
  }

  if (!is.null(todayBtn)) {
    if (todayBtn == "linked") {
      inputTag$attribs$`data-date-today-btn` <- "linked"
    } else if (todayBtn) {
      inputTag$attribs$`data-date-today-btn` <- "true"
    }
  }

  if (!is.null(todayHighlight) && todayHighlight)
    inputTag$attribs$`data-date-today-highlight` <- "true"

  if (!is.null(toggleActive) && toggleActive)
    inputTag$attribs$`data-date-toggle-active` <- "true"

  if (!is.null(clearBtn) && clearBtn)
    inputTag$attribs$`data-date-clear-btn` <- "true"

  if (!is.null(datesDisabled)) {
    datesDisabled <- paste0(
      '["',
      paste(
        lapply(datesDisabled,
          function(x) if (inherits(x, "Date")) format(x, "%Y-%m-%d") else x
        ),
        collapse = '","'
      ),
      '"]'
    )
    inputTag$attribs$`data-date-dates-disabled` <- datesDisabled
  }

  if (!is.null(daysOfWeekDisabled)) {
    daysOfWeekDisabled <- paste0(
      "[",
      paste(daysOfWeekDisabled, collapse = ","),
      "]"
    )
    inputTag$attribs$`data-date-days-of-week-disabled` <- daysOfWeekDisabled
  }

  if (!is.null(daysOfWeekHighlighted)) {
    daysOfWeekHighlighted <- paste0(
      "[",
      paste(daysOfWeekHighlighted, collapse = ","),
      "]"
    )
    inputTag$attribs$`data-date-days-of-week-highlighted` <- daysOfWeekHighlighted
  }

  if (!is.null(calendarWeeks) && calendarWeeks)
    inputTag$attribs$`data-date-calendar-weeks` <- "true"

  if (!is.null(immediateUpdates) && immediateUpdates)
    inputTag$attribs$`data-date-immediate-updates` <- "true"

  if (!is.null(keyboardNavigation) && !keyboardNavigation)
    inputTag$attribs$`data-date-keyboard-navigation` <- "false"

  tags$div(id = inputId,
    class = "shiny-date-input form-group shiny-input-container",
    style = if (!is.null(width)) paste0("width: ", validateCssUnit(width), ";"),

    controlLabel(inputId, label),
    inputTag,
    datePickerDependency
  )
}

datePickerDependency <- htmlDependency(
  "bootstrap-datepicker", "1.6.4", c(href = "shared/datepicker"),
  script = "js/bootstrap-datepicker.min.js",
  stylesheet = "css/bootstrap-datepicker3.min.css",
  # Need to enable noConflict mode. See #1346.
  head = "<script>
(function() {
  var datepicker = $.fn.datepicker.noConflict();
  $.fn.bsDatepicker = datepicker;
})();
</script>"
)
