#' Create date range input
#'
#' Creates a pair of text inputs which, when clicked on, bring up calendars that
#' the user can click on to select dates.
#'
#' The date \code{format} string specifies how the date will be displayed in
#' the browser. It allows the following values:
#'
#' \itemize{
#'   \item \code{yy} Year without century (12)
#'   \item \code{yyyy} Year with century (2012)
#'   \item \code{mm} Month number, with leading zero (01-12)
#'   \item \code{m} Month number, without leading zero (1-12)
#'   \item \code{M} Abbreviated month name
#'   \item \code{MM} Full month name
#'   \item \code{dd} Day of month with leading zero
#'   \item \code{d} Day of month without leading zero
#'   \item \code{D} Abbreviated weekday name
#'   \item \code{DD} Full weekday name
#' }
#'
#' @inheritParams dateInput
#' @param start The initial start date. Either a Date object, or a string in
#'   \code{yyyy-mm-dd} format. If NULL (the default), will use the current
#'   date in the client's time zone.
#' @param end The initial end date. Either a Date object, or a string in
#'   \code{yyyy-mm-dd} format. If NULL (the default), will use the current
#'   date in the client's time zone.
#' @param separator String to display between the start and end input boxes.
#' @param autoclose Close immediately when a date is selected (\code{TRUE} or
#'   \code{FALSE}).
#' @param multidate Enable multidate. Either \code{TRUE} or \code{FALSE} or an
#'   integer stating how  many dates can be selected, dropping the oldest dates
#'   from the list when the number is exceeded. The input's value is set to a
#'   string generated by joining the dates, formatted, with
#'   \code{multidateSeparator}.
#' @param multidateSeparator The string that will appear between dates when
#'   generating the multidate input's value.
#' @param orientation Location of the popup's anchor. A space-separated string
#'   consisting of one or two of \code{left} or \code{right}, \code{top}
#'   or \code{bottom}, and \code{auto}.
#' @param title Title on the top of the date picker.
#' @param todayBtn Display a "Today" button. If \code{TRUE} it will move the
#'   current date into view. If \code{"linked"} the current date will also be
#'   selected.
#' @param todayHighlight Highlight the current date.
#' @param toggleActive If \code{TRUE}, selecting the currently active date in
#'   the datepicker will unset the respective date. Always \code{TRUE} when
#'   multidate is being used.
#' @param calendarWeeks Show week numbers to the left of week rows (\code{TRUE}
#' or \code{FALSE}).
#' @param clearBtn Display a "Clear" button (\code{TRUE} or \code{FALSE}).
#' @param datesDisabled Disabled dates. Either a Date object, a string
#'   in \code{yyyy-mm-dd} format or a vector.
#' @param daysOfWeekDisabled Disabled days of week. Should be an integer from 0
#'   (Sunday) to 6 (Saturday) or a vector.
#' @param daysOfWeekHighlighted Highlighted days of week. Should be an integer
#'   from 0 (Sunday) to 6 (Saturday) or a vector.
#' @param immediateUpdates Update the input value immediately when selecting a
#'   year or month (\code{TRUE} or \code{FALSE}).
#' @param keyboardNavigation Allow date navigation by arrow keys (\code{TRUE} or
#'   \code{FALSE}).
#'
#' @family input elements
#' @seealso \code{\link{dateInput}}, \code{\link{updateDateRangeInput}}
#'
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'
#' ui <- fluidPage(
#'   dateRangeInput("daterange1", "Date range:",
#'                  start = "2001-01-01",
#'                  end   = "2010-12-31"),
#'
#'   # Default start and end is the current date in the client's time zone
#'   dateRangeInput("daterange2", "Date range:"),
#'
#'   # start and end are always specified in yyyy-mm-dd, even if the display
#'   # format is different
#'   dateRangeInput("daterange3", "Date range:",
#'                  start  = "2001-01-01",
#'                  end    = "2010-12-31",
#'                  min    = "2001-01-01",
#'                  max    = "2012-12-21",
#'                  format = "mm/dd/yy",
#'                  separator = " - "),
#'
#'   # Pass in Date objects
#'   dateRangeInput("daterange4", "Date range:",
#'                  start = Sys.Date()-10,
#'                  end = Sys.Date()+10),
#'
#'   # Use different language and different first day of week
#'   dateRangeInput("daterange5", "Date range:",
#'                  language = "de",
#'                  weekstart = 1),
#'
#'   # Start with decade view instead of default month view
#'   dateRangeInput("daterange6", "Date range:",
#'                  startview = "decade")
#' )
#'
#' shinyApp(ui, server = function(input, output) { })
#' }
#' @export
dateRangeInput <- function(inputId, label, start = NULL, end = NULL,
  min = NULL, max = NULL, format = "yyyy-mm-dd", startview = "month",
  weekstart = 0, language = "en", separator = " to ", autoclose = FALSE,
  multidate = FALSE, multidateSeparator = ",", orientation = "auto",
  title = NULL, todayBtn = FALSE, todayHighlight = FALSE,
  toggleActive = FALSE, calendarWeeks = FALSE, clearBtn = FALSE,
  datesDisabled = NULL, daysOfWeekDisabled = NULL, daysOfWeekHighlighted = NULL,
  immediateUpdates = FALSE, keyboardNavigation = TRUE, width = NULL) {

  # If start and end are date objects, convert to a string with yyyy-mm-dd format
  # Same for min and max
  if (inherits(start, "Date"))  start <- format(start, "%Y-%m-%d")
  if (inherits(end,   "Date"))  end   <- format(end,   "%Y-%m-%d")
  if (inherits(min,   "Date"))  min   <- format(min,   "%Y-%m-%d")
  if (inherits(max,   "Date"))  max   <- format(max,   "%Y-%m-%d")

  restored <- restoreInput(id = inputId, default = list(start, end))
  start <- restored[[1]]
  end <- restored[[2]]

  inputTag <- tags$input(
    class = "input-sm form-control",
    type = "text",
    `data-date-language` = language,
    `data-date-week-start` = weekstart,
    `data-date-format` = format,
    `data-date-start-view` = startview,
    `data-date-multidate-separator` = multidateSeparator,
    `data-date-orientation` = orientation,
    `data-date-title` = title,
    `data-min-date` = min,
    `data-max-date` = max
  )

  if (!is.null(autoclose) && autoclose)
    inputTag$attribs$`data-date-autoclose` <- "true"

  # When numeric, multidate is the maximum number of dates that can be selected
  if (!is.null(multidate) && multidate == T) {
    if (is.numeric(multidate)) {
      inputTag$attribs$`data-date-multidate` <- multidate
    } else {
      inputTag$attribs$`data-date-multidate` <- "true"
    }
  }

  if (!is.null(todayBtn)) {
    if (todayBtn == "linked") {
      inputTag$attribs$`data-date-today-btn` <- "linked"
    } else if (todayBtn) {
      inputTag$attribs$`data-date-today-btn` <- "true"
    }
  }

  if (!is.null(todayHighlight) && todayHighlight)
    inputTag$attribs$`data-date-today-highlight` <- "true"

  if (!is.null(toggleActive) && toggleActive)
    inputTag$attribs$`data-date-toggle-active` <- "true"

  if (!is.null(clearBtn) && clearBtn)
    inputTag$attribs$`data-date-clear-btn` <- "true"

  if (!is.null(datesDisabled)) {
    datesDisabled <- paste0(
      '["',
      paste(
        lapply(datesDisabled,
               function(x) if (inherits(x, "Date")) format(x, "%Y-%m-%d") else x
        ),
        collapse = '","'
      ),
      '"]'
    )
    inputTag$attribs$`data-date-dates-disabled` <- datesDisabled
  }

  if (!is.null(daysOfWeekDisabled)) {
    daysOfWeekDisabled <- paste0(
      "[",
      paste(daysOfWeekDisabled, collapse = ","),
      "]"
    )
    inputTag$attribs$`data-date-days-of-week-disabled` <- daysOfWeekDisabled
  }

  if (!is.null(daysOfWeekHighlighted)) {
    daysOfWeekHighlighted <- paste0(
      "[",
      paste(daysOfWeekHighlighted, collapse = ","),
      "]"
    )
    inputTag$attribs$`data-date-days-of-week-highlighted` <- daysOfWeekHighlighted
  }

  if (!is.null(calendarWeeks) && calendarWeeks)
    inputTag$attribs$`data-date-calendar-weeks` <- "true"

  if (!is.null(immediateUpdates) && immediateUpdates)
    inputTag$attribs$`data-date-immediate-updates` <- "true"

  if (!is.null(keyboardNavigation) && !keyboardNavigation)
    inputTag$attribs$`data-date-keyboard-navigation` <- "false"

  attachDependencies(
    div(id = inputId,
      class = "shiny-date-range-input form-group shiny-input-container",
      style = if (!is.null(width)) paste0("width: ", validateCssUnit(width), ";"),

      controlLabel(inputId, label),
      # input-daterange class is needed for dropdown behavior
      div(class = "input-daterange input-group",
        tagAppendAttributes(inputTag, `data-initial-date` = start),
        span(class = "input-group-addon", separator),
        tagAppendAttributes(inputTag, `data-initial-date` = end)
      )
    ),
    datePickerDependency
  )
}
